# See https://pre-commit.com for more information
repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # Black - Python code formatter (optional, can be used alongside ruff)
  - repo: https://github.com/psf/black
    rev: 24.12.0
    hooks:
      - id: black
        language_version: python3.10

  # Pylint - Python linter for code quality
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        require_serial: true
        args:
          - --rcfile=.pylintrc
          - --fail-under=8

  # Trailing whitespace and file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']