# Completion and Success Messages

success:
  - "Excellent! {script} completed successfully!"
  - "Mission accomplished! {script} finished without errors."
  - "Great news! {script} ran perfectly and completed."
  - "Success! {script} is done and everything worked."
  - "Perfect execution! {script} completed all tasks."

failure:
  - "Unfortunately, {script} failed to complete. Check the error details."
  - "Bad news: {script} encountered an error and couldn't finish."
  - "Failure alert: {script} stopped due to an error."
  - "Problem! {script} failed during execution."

partial:
  - "{script} partially completed. Some tasks finished, but issues occurred."
  - "Mixed results: {script} completed some operations but encountered problems."
  - "Partial success: {script} finished with warnings or minor errors."

timeout:
  - "Time's up! {script} was stopped after reaching the timeout limit."
  - "Timeout reached: {script} was terminated for taking too long."
  - "Time limit exceeded: {script} was automatically stopped."

interrupted:
  - "User override: {script} was manually stopped."
  - "Cancelled: {script} was interrupted by user request."
  - "Manual stop: {script} execution was terminated by user."

quick_task:
  - "Lightning fast! {script} finished in record time."
  - "Speed demon! {script} completed very quickly."
  - "Rapid execution! {script} is done already."

slow_task:
  - "Finally! {script} took its time but completed successfully."
  - "Worth the wait! {script} finished after a long runtime."
  - "Patience paid off! {script} completed after extended processing."

resource_intensive:
  - "Heavy lifting done! {script} completed its resource-intensive task."
  - "Processing powerhouse! {script} finished the demanding workload."
  - "System workout complete! {script} handled the intensive processing."

batch_complete:
  - "All done! The entire batch of scripts has completed."
  - "Batch processing finished! All scripts in the sequence are complete."
  - "Full automation cycle complete! All scripts successful."

sequence_success:
  - "Orchestration sequence completed! All scripts ran in perfect harmony."
  - "Workflow success! The entire script sequence executed flawlessly."
  - "Automation pipeline complete! Every step finished successfully."

first_run:
  - "First run successful! {script} executed perfectly on its initial attempt."
  - "Debut performance! {script} completed successfully on first execution."
  - "Perfect start! {script} ran flawlessly on its maiden voyage."