name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run Ruff linting
      run: |
        uv run ruff check --fix .
        uv run ruff format .
        UNSAFE_COUNT=$(uv run ruff check --output-format=text . 2>&1 | grep -c "unsafe-fixes" || true)
        if [ $UNSAFE_COUNT -gt 0 ]; then
          echo "ℹ️ $UNSAFE_COUNT hidden fixes can be enabled with the '--unsafe-fixes' option"
        fi
        uv run ruff check .

    - name: Run Ruff formatting check
      run: uv run ruff format --check .
    
    - name: Run Pylint
      run: |
        # Find all Python files (excluding venv and hidden dirs)
        PYTHON_FILES=$(find . -type f -name "*.py" -not -path "./.venv/*" -not -path "./venv/*" -not -path "./.git/*" -not -path "./old-scripts/*" | grep -E "^\./(main|gui|dashboard|cli)\.py$|^\./(modules|scripts)/.*\.py$" || true)
        if [ -n "$PYTHON_FILES" ]; then
          uv run pylint $PYTHON_FILES --fail-under=7.0 --disable=import-error,too-many-positional-arguments || true
        fi