name: 🔬 Static Application Security Testing

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  # CodeQL disabled for template repository (no application code)
  # Uncomment when using in production repositories with actual code
  # codeql:
  #   name: CodeQL Analysis
  #   runs-on: ubuntu-latest
  #
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: [ 'javascript' ]  # Only analyze JS since Python code is minimal
  #
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v5
  #
  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v3
  #     with:
  #       languages: ${{ matrix.language }}
  #
  #   - name: Autobuild
  #     uses: github/codeql-action/autobuild@v3
  #
  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v3

  codeql-placeholder:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Skip CodeQL for template repository
      run: |
        echo "✅ CodeQL analysis skipped for template repository"
        echo "This workflow library contains no application code to analyze"
        echo "Enable CodeQL when using in production repositories"

  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run Semgrep
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/docker
        generateSarif: "1"

    # SARIF upload disabled for template repository
    # Uncomment when using in production repositories with proper permissions
    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: semgrep.sarif
    #   if: always()